<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^(.*)\s+\((.*)\)$</string>
	<key>foldingStopMarker</key>
	<string>^==========$</string>
	<key>keyEquivalent</key>
	<string>^~K</string>
	<key>name</key>
	<string>Kindle</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.underline</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(.*)\s+\((.*)\)$</string>
			<key>name</key>
			<string>markup.heading.1</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^==========$</string>
			<key>name</key>
			<string>meta.separator</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\-.*$</string>
			<key>contentName</key>
			<string>markup.quote</string>
			<key>end</key>
			<string>^==========$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^-\s*(.*)\s*\|\s*Added on\s*(.*)$</string>
			<key>name</key>
			<string>meta.other</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>separator-line</key>
		<dict>
			<key>match</key>
			<string>^==========$</string>
		</dict>
		<key>title-line</key>
		<dict>
			<key>match</key>
			<string>^(.*)\s+\((.*)\)$</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.kindle</string>
	<key>uuid</key>
	<string>C5FB34D9-AD31-4785-8EFB-FA99A3E94DDF</string>
</dict>
</plist>
